services:
  influxdb:
    image: influxdb:2.6
    container_name: c1vh-influxdb
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - influx_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - monitor_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      retries: 5

  telegraf:
    image: telegraf:1.24
    container_name: c1vh-telegraf
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./telegraf/config.ini:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      influxdb:
        condition: service_healthy
    networks:
      - monitor_net

networks:
  monitor_net:
    external: true
    name: c1vh_monitor_net

volumes:
  influx_data:

