services:
  nginx:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./sites:/etc/nginx/sites
      - ./certs:/etc/nginx/certs
    depends_on:
      - flask-app
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    name: c1vh_app_net
    external: true
