server {
    listen 80 default_server;

    server_name _;

    # Логгирование (чтоб видеть мусорные запросы)
    access_log /var/log/nginx/default_access.log;
    error_log  /var/log/nginx/default_error.log warn;

    root /public;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
