services:
  postgres:
    image: postgres:15
    container_name: c1vh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db_net

  adminer:
    image: adminer:latest
    container_name: c1vh-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - db_net

networks:
  db_net:
    external: true

volumes:
  pg_data:

