services:
  postgres:
    image: postgres:latest
    container_name: c1vh-postgres
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - db_net

  adminer:
    image: adminer:latest
    container_name: c1vh-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - db_net

networks:
  db_net:
    external: true
    name: c1vh_db_net

volumes:
  pg_data:

