services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "0.0.0.0:81:81"  # Web UI
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - app_net
